In [ ]:
import pandas as pd
import numpy as np

In [ ]:
a=pd.Series([1,2,3,4,5,6,6])
a

0    1
1    2
2    3
3    4
4    5
5    6
6    6
dtype: int64

In [ ]:
x={
    'name':["akash","naksh","gaurav","piyush"],
    'age':[21,23,24,np.nan],
    'city':['kota','jaipur','up','mp'],
}
df=pd.DataFrame(x)

In [ ]:
df

     name   age    city
0   akash  21.0    kota
1   naksh  23.0  jaipur
2  gaurav  24.0      up
3  piyush   NaN      mp

In [ ]:
df.shape

(4, 3)

In [ ]:
df.dtypes

name     object
age     float64
city     object
dtype: object

In [ ]:
df.columns

Index(['name', 'age', 'city'], dtype='object')

In [ ]:
df['age']

0    21.0
1    23.0
2    24.0
3     NaN
Name: age, dtype: float64

In [ ]:
df.loc[0]

name    akash
age      21.0
city     kota
Name: 0, dtype: object

In [ ]:
df.iloc[0]

name    akash
age      21.0
city     kota
Name: 0, dtype: object

In [ ]:
df[df['age']>21]

     name   age    city
1   naksh  23.0  jaipur
2  gaurav  24.0      up

In [ ]:
df[(df['age']>21) & (df['city']=='jaipur')]

    name   age    city
1  naksh  23.0  jaipur

In [ ]:
df.sort_values('age' ,ascending=False)

     name   age    city
2  gaurav  24.0      up
1   naksh  23.0  jaipur
0   akash  21.0    kota
3  piyush   NaN      mp

In [ ]:
df['city'].value_counts()

city
kota      1
jaipur    1
up        1
mp        1
Name: count, dtype: int64

In [ ]:
df['city'][1] = 'dolly'

/tmp/ipython-input-215632858.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['city'][1] = 'dolly'
/tmp/ipython-input-215632858.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['city'][1] = 'dolly'

In [ ]:
df['city']

0     kota
1    dolly
2       up
3       mp
Name: city, dtype: object

In [ ]:
df[df['age'] >= 18][['city', 'name']]

    city    name
0   kota   akash
1  dolly   naksh
2     up  gaurav

In [ ]:
df.sort_values('age',ascending=False)

     name   age   city
2  gaurav  24.0     up
1   naksh  23.0  dolly
0   akash  21.0   kota
3  piyush   NaN     mp

In [ ]:
df['city'].value_counts()

city
kota     1
dolly    1
up       1
mp       1
Name: count, dtype: int64

In [ ]:
df.isnull().sum()

name    0
age     1
city    0
dtype: int64

In [ ]:
# df['age'] = df['age'].fillna(df['age'].mean())

In [ ]:
df

     name   age   city
0   akash  21.0   kota
1   naksh  23.0  dolly
2  gaurav  24.0     up
3  piyush   NaN     mp

In [ ]:
#df.drop('age',axis=0, inplace=True)

In [ ]:
df

     name   age   city
0   akash  21.0   kota
1   naksh  23.0  dolly
2  gaurav  24.0     up
3  piyush   NaN     mp

In [ ]:
df['age'].astype=int

In [ ]:
df.isnull().sum()

name    0
age     1
city    0
dtype: int64

In [ ]:
df['age']=df['age'].fillna(df['age'].mean())

In [ ]:
df

     name        age   city
0   akash  21.000000   kota
1   naksh  23.000000  dolly
2  gaurav  24.000000     up
3  piyush  22.666667     mp

In [ ]:
df['age']=df['age'].astype (int)

In [ ]:
df

     name  age   city
0   akash   21   kota
1   naksh   23  dolly
2  gaurav   24     up
3  piyush   22     mp

In [ ]:
df.groupby('city')['age'].mean()

city
dolly    23.0
kota     21.0
mp       22.0
up       24.0
Name: age, dtype: float64

In [ ]:
df.groupby('city')['age'].sum()

city
dolly    23
kota     21
mp       22
up       24
Name: age, dtype: int64

In [ ]:
df.groupby('city')['name'].value_counts()

city   name
dolly  naksh     1
kota   akash     1
mp     piyush    1
up     gaurav    1
Name: count, dtype: int64

In [ ]:
df=pd.read_csv("/content/Attrition - Attrition.csv")

In [ ]:
df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [ ]:
x=df.drop(columns=['Attrition'])

In [ ]:
df['Attrition']=df['Attrition'].map({"Yes":0,"No":1})

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
y=df['Attrition']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,
test_size=0.2,random_state=42)

In [ ]:
print(x.shape)
print(x_test.shape)
print(x_train.shape)

print(y_train.shape)
print(y_test.shape)
print(y.shape)

(1470, 34)
(294, 34)
(1176, 34)
(1176,)
(294,)
(1470,)