In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df1 = pd.read_csv('/content/Attrition - Attrition.csv')
df2 = pd.read_csv('/content/linkedin-reviews - linkedin-reviews (1).csv')

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [ ]:
df2.isnull().sum()

Review    0
Rating    0
dtype: int64

In [ ]:
df1.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [ ]:
df1['Attrition'].value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [ ]:
df1['Attrition'] = df1['Attrition'].map({'Yes':1,'No':2})

In [ ]:
df1.groupby('BusinessTravel').size()

BusinessTravel
Non-Travel            150
Travel_Frequently     277
Travel_Rarely        1043
dtype: int64

In [ ]:
df1['BusinessTravel'] = df1['BusinessTravel'].map({'Travel_Rarely':1,'Travel_Frequently':2,'Non-Travel':3})

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   int64
 2   BusinessTravel            1470 non-null   int64
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   int64
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(29), object(6)
memory usage: 402.1+ KB

In [ ]:
df1.groupby(df1['Department']).size()

Department
Human Resources            63
Research & Development    961
Sales                     446
dtype: int64

In [ ]:
df1['Department'] = df1['Department'].map({'Sales':1,'Research & Development':2,'Human Resources':3})

In [ ]:
df1.groupby(df1['EducationField']).size()

EducationField
Human Resources      27
Life Sciences       606
Marketing           159
Medical             464
Other                82
Technical Degree    132
dtype: int64

In [ ]:
df1.drop(columns = ['EducationField'] ,inplace = True)

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 34 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   int64
 2   BusinessTravel            1470 non-null   int64
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   int64
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EmployeeCount             1470 non-null   int64
 8   EmployeeNumber            1470 non-null   int64
 9   EnvironmentSatisfaction   1470 non-null   int64
 10  Gender                    1470 non-null   int64
 11  HourlyRate                1470 non-null   int64
 12  JobInvolvement            1470 non-null   int64
 13  JobLevel                  1470 non-null   int64
 14  JobRole                   1470 non-null   object
 15  JobSatisfaction           1470 non-null   int64
 16  MaritalStatus             1470 non-null   object
 17  MonthlyIncome             1470 non-null   int64
 18  MonthlyRate               1470 non-null   int64
 19  NumCompaniesWorked        1470 non-null   int64
 20  Over18                    1470 non-null   object
 21  OverTime                  1470 non-null   object
 22  PercentSalaryHike         1470 non-null   int64
 23  PerformanceRating         1470 non-null   int64
 24  RelationshipSatisfaction  1470 non-null   int64
 25  StandardHours             1470 non-null   int64
 26  StockOptionLevel          1470 non-null   int64
 27  TotalWorkingYears         1470 non-null   int64
 28  TrainingTimesLastYear     1470 non-null   int64
 29  WorkLifeBalance           1470 non-null   int64
 30  YearsAtCompany            1470 non-null   int64
 31  YearsInCurrentRole        1470 non-null   int64
 32  YearsSinceLastPromotion   1470 non-null   int64
 33  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(30), object(4)
memory usage: 390.6+ KB

In [ ]:
df1.groupby(df1['Gender']).size()

Gender
Female    588
Male      882
dtype: int64

In [ ]:
df1['Gender'] = df1['Gender'].map({'Female':1,'Male':2})

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 33 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   int64
 2   BusinessTravel            1470 non-null   int64
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   int64
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EmployeeCount             1470 non-null   int64
 8   EmployeeNumber            1470 non-null   int64
 9   EnvironmentSatisfaction   1470 non-null   int64
 10  Gender                    1470 non-null   int64
 11  HourlyRate                1470 non-null   int64
 12  JobInvolvement            1470 non-null   int64
 13  JobLevel                  1470 non-null   int64
 14  JobSatisfaction           1470 non-null   int64
 15  MaritalStatus             1470 non-null   int64
 16  MonthlyIncome             1470 non-null   int64
 17  MonthlyRate               1470 non-null   int64
 18  NumCompaniesWorked        1470 non-null   int64
 19  Over18                    1470 non-null   object
 20  OverTime                  1470 non-null   object
 21  PercentSalaryHike         1470 non-null   int64
 22  PerformanceRating         1470 non-null   int64
 23  RelationshipSatisfaction  1470 non-null   int64
 24  StandardHours             1470 non-null   int64
 25  StockOptionLevel          1470 non-null   int64
 26  TotalWorkingYears         1470 non-null   int64
 27  TrainingTimesLastYear     1470 non-null   int64
 28  WorkLifeBalance           1470 non-null   int64
 29  YearsAtCompany            1470 non-null   int64
 30  YearsInCurrentRole        1470 non-null   int64
 31  YearsSinceLastPromotion   1470 non-null   int64
 32  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(31), object(2)
memory usage: 379.1+ KB

In [ ]:
df1.groupby(df1['JobRole']).size()

JobRole
Healthcare Representative    131
Human Resources               52
Laboratory Technician        259
Manager                      102
Manufacturing Director       145
Research Director             80
Research Scientist           292
Sales Executive              326
Sales Representative          83
dtype: int64

In [ ]:
df1.drop(columns = ['JobRole'], inplace = True)

In [ ]:
df1.groupby(df1['MaritalStatus']).size()

MaritalStatus
Divorced    327
Married     673
Single      470
dtype: int64

In [ ]:
df1['MaritalStatus'] = df1['MaritalStatus'].map({'Single':1,'Married':2,'Divorced':3})

In [ ]:
df1.groupby(df1['Over18']).size()

Over18
Y    1470
dtype: int64

In [ ]:
(df1['Over18'] == 'Y').count()

np.int64(1470)

In [ ]:
df1['Over18'] = df1['Over18'].map({'Y':1,'N':2})

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 33 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   int64
 2   BusinessTravel            1470 non-null   int64
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   int64
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EmployeeCount             1470 non-null   int64
 8   EmployeeNumber            1470 non-null   int64
 9   EnvironmentSatisfaction   1470 non-null   int64
 10  Gender                    1470 non-null   int64
 11  HourlyRate                1470 non-null   int64
 12  JobInvolvement            1470 non-null   int64
 13  JobLevel                  1470 non-null   int64
 14  JobSatisfaction           1470 non-null   int64
 15  MaritalStatus             1470 non-null   int64
 16  MonthlyIncome             1470 non-null   int64
 17  MonthlyRate               1470 non-null   int64
 18  NumCompaniesWorked        1470 non-null   int64
 19  Over18                    1470 non-null   int64
 20  OverTime                  1470 non-null   object
 21  PercentSalaryHike         1470 non-null   int64
 22  PerformanceRating         1470 non-null   int64
 23  RelationshipSatisfaction  1470 non-null   int64
 24  StandardHours             1470 non-null   int64
 25  StockOptionLevel          1470 non-null   int64
 26  TotalWorkingYears         1470 non-null   int64
 27  TrainingTimesLastYear     1470 non-null   int64
 28  WorkLifeBalance           1470 non-null   int64
 29  YearsAtCompany            1470 non-null   int64
 30  YearsInCurrentRole        1470 non-null   int64
 31  YearsSinceLastPromotion   1470 non-null   int64
 32  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(32), object(1)
memory usage: 379.1+ KB

In [ ]:
df1.groupby(df1['OverTime']).size()

OverTime
No     1054
Yes     416
dtype: int64

In [ ]:
df1['OverTime'] = df1['OverTime'].map({'Yes':1,'No':2})

In [ ]:
df1

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,1,1102,1,1,2,1,1,2,...,1,80,0,8,0,1,6,4,0,5
1,49,2,2,279,2,8,1,1,2,3,...,4,80,1,10,3,3,10,7,1,7
2,37,1,1,1373,2,2,2,1,4,4,...,2,80,0,7,3,3,0,0,0,0
3,33,2,2,1392,2,3,4,1,5,4,...,3,80,0,8,3,3,8,7,3,0
4,27,2,1,591,2,2,1,1,7,1,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,2,2,884,2,23,2,1,2061,3,...,3,80,1,17,3,3,5,2,0,3
1466,39,2,1,613,2,6,1,1,2062,4,...,1,80,1,9,5,3,7,7,1,7
1467,27,2,1,155,2,4,3,1,2064,2,...,2,80,1,6,0,3,6,2,0,3
1468,49,2,2,1023,1,2,3,1,2065,4,...,4,80,0,17,3,2,9,6,0,8
1469,34,2,1,628,2,8,3,1,2068,2,...,1,80,0,6,3,4,4,3,1,2

In [ ]:
df1['Gender'].value_counts()

Gender
2    882
1    588
Name: count, dtype: int64

In [ ]:
df2

                                                Review  Rating
0    Does absolutely nothing for a LinkedIn beginne...       1
1                              Force close(galaxy tab)       1
2    Slow and it tries to upload your contacts with...       1
3    Add ability to customize the profile and move ...       4
4    Good app, but it's a pain that it's not possib...       4
..                                                 ...     ...
697  Can't trust, Going to uninstall just for that ...       1
698  It really gets me linked in with my friends. H...       5
699  It lacks most of what makes the other social n...       4
700  Really disappointed in the new version. Seems ...       2
701  One of the best looking and well designed apps...       5

[702 rows x 2 columns]

In [ ]:
male_y= df1[(df1['Gender'] == 1 & (df1['Attrition'] == 1))]

In [ ]:
female_y = df1[(df1['Gender'] == 2 & (df1['Attrition'] == 1))]

In [ ]:
male_n = df1[(df1['Gender'] == 1 & (df1['Attrition'] == 2))]

In [ ]:
female_n = df1[(df1['Gender'] == 2 ) & (df1['Attrition'] == 2)]

In [ ]:
female_n

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1,49,2,2,279,2,8,1,1,2,3,...,4,80,1,10,3,3,10,7,1,7
4,27,2,1,591,2,2,1,1,7,1,...,4,80,1,6,3,3,2,2,2,2
5,32,2,2,1005,2,2,2,1,8,4,...,3,80,0,8,2,2,7,7,3,6
7,30,2,1,1358,2,24,1,1,11,4,...,2,80,1,1,2,3,1,0,0,0
8,38,2,2,216,2,23,3,1,12,4,...,2,80,0,10,2,3,9,7,1,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,2,2,884,2,23,2,1,2061,3,...,3,80,1,17,3,3,5,2,0,3
1466,39,2,1,613,2,6,1,1,2062,4,...,1,80,1,9,5,3,7,7,1,7
1467,27,2,1,155,2,4,3,1,2064,2,...,2,80,1,6,0,3,6,2,0,3
1468,49,2,2,1023,1,2,3,1,2065,4,...,4,80,0,17,3,2,9,6,0,8
1469,34,2,1,628,2,8,3,1,2068,2,...,1,80,0,6,3,4,4,3,1,2

In [ ]:
male_n

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
3,33,2,2,1392,2,3,4,1,5,4,...,3,80,0,8,3,3,8,7,3,0
6,59,2,1,1324,2,3,3,1,10,3,...,1,80,3,12,3,2,1,0,0,0
11,29,2,1,153,2,15,2,1,15,4,...,4,80,0,10,3,3,9,5,0,8
15,29,2,1,1389,2,21,4,1,20,2,...,3,80,1,10,1,3,10,9,8,8
18,53,2,1,1219,1,2,4,1,23,1,...,3,80,0,31,3,3,25,8,3,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1457,40,2,1,1194,2,2,4,1,2051,3,...,2,80,3,20,2,3,5,3,0,2
1458,35,2,1,287,2,1,4,1,2052,3,...,4,80,1,4,5,3,4,3,1,1
1460,29,2,1,468,2,28,4,1,2054,4,...,2,80,0,5,3,1,5,4,0,4
1462,39,2,1,722,1,24,1,1,2056,2,...,1,80,1,21,2,2,20,9,9,6
1464,26,2,1,1167,1,5,3,1,2060,4,...,4,80,0,5,2,3,4,2,0,0

In [ ]:
female # here there is 0 rows because theere is no female with attrition 1

Empty DataFrame
Columns: [Age, Attrition, BusinessTravel, DailyRate, Department, DistanceFromHome, Education, EmployeeCount, EmployeeNumber, EnvironmentSatisfaction, Gender, HourlyRate, JobInvolvement, JobLevel, JobSatisfaction, MaritalStatus, MonthlyIncome, MonthlyRate, NumCompaniesWorked, Over18, OverTime, PercentSalaryHike, PerformanceRating, RelationshipSatisfaction, StandardHours, StockOptionLevel, TotalWorkingYears, TrainingTimesLastYear, WorkLifeBalance, YearsAtCompany, YearsInCurrentRole, YearsSinceLastPromotion, YearsWithCurrManager]
Index: []

[0 rows x 33 columns]

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 702 entries, 0 to 701
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Review  702 non-null    object
 1   Rating  702 non-null    int64
dtypes: int64(1), object(1)
memory usage: 11.1+ KB

In [ ]:
def rat(x):
  if x <= 2:
    return 'Bad'
  elif x == 3:
    return 'Avg'
  else:
    return  'Good'


df2['Rating'] = df2['Rating'].map(rat)

In [ ]:
df2['Rating'].sample()

438    Good
Name: Rating, dtype: object

In [ ]:
bad = df2[df2['Rating'] == 'Bad']
avg = df2[df2['Rating'] == 'Avg']
good = df2[df2['Rating'] == 'Good']

In [ ]:
bad

                                                Review Rating
0    Does absolutely nothing for a LinkedIn beginne...    Bad
1                              Force close(galaxy tab)    Bad
2    Slow and it tries to upload your contacts with...    Bad
5    This app is poor and bad. Linkedin app on my H...    Bad
11   Piece of s**t app. Really? You want people to ...    Bad
..                                                 ...    ...
685                    it's worse than the old one....    Bad
686  HATE the new update/layout!!! So hard to look ...    Bad
694  Yikes... Talk about losing focus on your targe...    Bad
697  Can't trust, Going to uninstall just for that ...    Bad
700  Really disappointed in the new version. Seems ...    Bad

[364 rows x 2 columns]

In [ ]:
good

                                                Review Rating
3    Add ability to customize the profile and move ...   Good
4    Good app, but it's a pain that it's not possib...   Good
6                                              Finally   Good
7    Have been using DroidIn. Ability to move to SD...   Good
8                     Works fine on Samsung Captivate.   Good
..                                                 ...    ...
693  Ok app - needs to be transferable to SD card s...   Good
695                  Quick and easy to use. Great app!   Good
698  It really gets me linked in with my friends. H...   Good
699  It lacks most of what makes the other social n...   Good
701  One of the best looking and well designed apps...   Good

[217 rows x 2 columns]

In [ ]:
df=pd.read_csv("/content/linkedin-reviews.csv")

NameError: name 'pd' is not defined